
[general]

	[general.settings]
		disable_warp_message = false
		color_tag_replacor = true
		dice = true
		color_tag = 5
		party_invite_message_editor = true
		dark_auction_alert = true
		my_setting = true
		show_container_inventory_when_opened = false
		show_container_inventory_on_click = false
		stash_message = true
		inq_detector = true
		change_stash_open = 0
		hide_falling_blocks = false
		replace_ah_message = true
		jacob_start_alert = true
		change_stash_action = 0
		coin_flip = true

